### ISSUE TITLE
Trying to create ingress type of aws alb ,also adds default annotations set in helm chart

### ISSUE THREAD

**Issue by taragurung** [dirsigler/uptime-kuma-helm#179]
I am trying to create ingress of type AWS ALB but as the helm chart has the default annotation related to nginx causing me an issues. What is the annotation set by default?

`ingress.annotations."nginx.ingress.kubernetes.io/server-snippets"`

If I want to use ALB it may not make sense, any way to ignore it , coz I am just trying to have annotation related to aws alb

**1. uptime kuma --version 2.19.3
   2. made changes to setup ingress as follows:**
   
```
ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:8xxxx:certificate/c13250b9-xxxx-xxx-8xx-xxxaca8a40
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
  enabled: true
  ingressClass: alb
  extraLabels: {}
  hosts:
  - host: uptime.mywebsite.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
```
