### ISSUE TITLE
How to disable clusterIP when use helm chart?

### ISSUE THREAD

**Issue by xpo-mie** [dirsigler/uptime-kuma-helm#185]
How to add ClusterIP: None ?

```
service:
  type: ClusterIP
  port: 3001
  nodePort:
  annotations: {}
```
